global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'blackbox'
    file_sd_configs:
      - files: ['targets.json']
    relabel_configs:
      - source_labels: ['colo', 'origin_url']
        separator: '/'
        target_label: '__metrics_path__'
        replacement: '/probe/$1'

